---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: nationalparks-js
spec:
  params:
    - name: git-revision
    - name: git-commit-message
    - name: git-repo-url
    - name: git-repo-name
    - name: content-type
    - name: pusher-name
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        labels:
          tekton.dev/pipeline: nationalparks-js-pipeline
        name: nationalparks-js-deploy-$(uid)
      spec:
        params:
          - name: APP_NAME
            value: nationalparks-js
          - name: GIT_REPO
            value: $(tt.params.git-repo-url)
          - name: GIT_REVISION
            value: $(tt.params.git-revision)
        pipelineRef:
          name: nationalparks-js-pipeline
        workspaces:
        - name: workspace
          persistentVolumeClaim:
            claimName: app-source-pvc-js
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: nationalparks-js
spec:
  params:
  - name: git-repo-url
    value: $(body.repository.clone_url)
  - name: git-repo-name
    value: $(body.repository.name)
  - name: git-revision
    value: $(body.after)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: nationalparks-js
spec:
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - ref: nationalparks-js
    template:
      ref: nationalparks-js
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: nationalparks-js
  name: el-nationalparks-js
spec:
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-nationalparks-js
    weight: 100
